use_frameworks!

platform :ios, '13.0'

flutter_application_path = File.expand_path('flutter_module', __dir__)
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'KKFlutterInspectorKit_Example' do
  pod 'KKFlutterInspectorKit', :path => '../'
  install_all_flutter_pods(flutter_application_path)

  target 'KKFlutterInspectorKit_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  flutter_post_install(installer)
end
