use_frameworks!

platform :ios, '12.0'

target 'KKFlutterInspectorKit_Example' do
  pod 'KKFlutterInspectorKit', :path => '../'

  target 'KKFlutterInspectorKit_Tests' do
    inherit! :search_paths

    
  end
end
